
export const RETRIEVE_DECKS_ACTION = "SHOW_DECKS_ACTION"
export const ADD_DECK_ACTION = "ADD_DECK_ACTION"
export const DELETE_DECK_ACTION = "DELETE_DECK_ACTION"

export const RETRIEVE_CARDS_ACTION = "SHOW_CARDS_ACTION"
export const ADD_CARD_ACTION = "ADD_CARD_ACTION"
export const DELETE_CARD_ACTION = "DELETE_CARD_ACTION"